package com.android_group10.needy;

public class Post {
    private int postId;
    private int postStatus;  // 1=Active, 2=In progress, 3=Finished
    private User user;
    private String description;
    private ServiceType serviceType;
    private String city;
    private String zipCode;
    private String incentive;

    public Post(User user, String description, ServiceType serviceType, String city, String zipCode, String incentive){
        //this.postId = postId; we should take the autogenerated one from DB
        this.user = user;
        this.postStatus = 1;  //1 = Active
        this.zipCode = zipCode;
        this.serviceType = serviceType;
        this.description = description;
        this.city = city;
        this.incentive = incentive;

        //   new City(city, zipCode);   //this might be changed if data is put into DB
    }


    public int getPostStatus() {
        return postStatus;
    }

    public void setIncentive(String incentive) {
        this.incentive = incentive;
    }

    public String getIncentive() {
        return incentive;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setPostStatus(int postStatus) {
        this.postStatus = postStatus;
    }

    public User getUser() {
        return user;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setServiceType(ServiceType serviceType) {
        this.serviceType = serviceType;
    }

    public String getZipCode() {
        return zipCode;
    }

    public String getCity() {
        return city;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getPostId() {
        //request DB
        return postId;
    }

    public ServiceType getServiceType() {
        return serviceType;
    }

    public String getDescription() {
        return description;
    }

    @Override
    public String toString() {
        return description;
    }
}
